export enum MusicGenre {
  ROCK = 'ROCK',
  POP = 'POP',
  JAZZ = 'JAZZ',
  CLASSICAL = 'CLASSICAL',
  HIP_HOP = 'HIP_HOP',
  REGGAE = 'REGGAE',
  BLUES = 'BLUES',
  ELECTRONIC = 'ELECTRONIC',
  COUNTRY = 'COUNTRY',
  FOLK = 'FOLK',
  METAL = 'METAL',
  PUNK = 'PUNK',
}
